# Generated by Django 4.0.1 on 2022-01-22 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dept2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.dept1')),
            ],
        ),
    ]
