# Generated by Django 4.0.1 on 2022-01-22 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0002_dept2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dept2',
            old_name='team',
            new_name='department',
        ),
    ]
