# Generated by Django 4.0.1 on 2022-01-24 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0003_rename_team_dept2_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dept1',
            name='dept_affairs',
        ),
        migrations.RemoveField(
            model_name='dept1',
            name='dept_loc',
        ),
        migrations.RemoveField(
            model_name='dept1',
            name='dept_team',
        ),
        migrations.RemoveField(
            model_name='dept2',
            name='department',
        ),
        migrations.RemoveField(
            model_name='dept2',
            name='name',
        ),
        migrations.RemoveField(
            model_name='dept2',
            name='number',
        ),
        migrations.RemoveField(
            model_name='dept2',
            name='position',
        ),
        migrations.AddField(
            model_name='dept2',
            name='dept_affairs',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='dept2',
            name='dept_loc',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dept2',
            name='dept_team',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='dept3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.dept2')),
            ],
        ),
    ]
