# Generated by Django 4.0.1 on 2022-01-24 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dept', '0004_remove_dept1_dept_affairs_remove_dept1_dept_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept2',
            name='dept_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dept.dept1'),
        ),
    ]
